// src/redux/constants/menuConstants.js

export const MENU_FETCH_REQUEST = "MENU_FETCH_REQUEST";
export const MENU_FETCH_SUCCESS = "MENU_FETCH_SUCCESS";
export const MENU_FETCH_FAIL = "MENU_FETCH_FAIL";

export const MENU_ADD_REQUEST = "MENU_ADD_REQUEST";
export const MENU_ADD_SUCCESS = "MENU_ADD_SUCCESS";
export const MENU_ADD_FAIL = "MENU_ADD_FAIL";

export const MENU_UPDATE_REQUEST = "MENU_UPDATE_REQUEST";
export const MENU_UPDATE_SUCCESS = "MENU_UPDATE_SUCCESS";
export const MENU_UPDATE_FAIL = "MENU_UPDATE_FAIL";

export const MENU_STATUS_UPDATE_REQUEST = "MENU_STATUS_UPDATE_REQUEST";
export const MENU_STATUS_UPDATE_SUCCESS = "MENU_STATUS_UPDATE_SUCCESS";
export const MENU_STATUS_UPDATE_FAIL = "MENU_STATUS_UPDATE_FAIL";

export const MENU_SEARCH_REQUEST = "MENU_SEARCH_REQUEST";
export const MENU_SEARCH_SUCCESS = "MENU_SEARCH_SUCCESS";
export const MENU_SEARCH_FAIL = "MENU_SEARCH_FAIL";
