export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_STATUS_UPDATE = "ORDER_STATUS_UPDATE";
export const ORDER_FILTERS_UPDATE = "ORDER_FILTERS_UPDATE";
export const ORDER_SEARCH_UPDATE = "ORDER_SEARCH_UPDATE";
export const ORDER_RESET_FILTERS = "ORDER_RESET_FILTERS";
