export const GET_SUBCATEGORIES_REQUEST = "GET_SUBCATEGORIES_REQUEST";
export const GET_SUBCATEGORIES_SUCCESS = "GET_SUBCATEGORIES_SUCCESS";
export const GET_SUBCATEGORIES_FAIL = "GET_SUBCATEGORIES_FAIL";

export const ADD_SUBCATEGORY_REQUEST = "ADD_SUBCATEGORY_REQUEST";
export const ADD_SUBCATEGORY_SUCCESS = "ADD_SUBCATEGORY_SUCCESS";
export const ADD_SUBCATEGORY_FAIL = "ADD_SUBCATEGORY_FAIL";


export const INACTIVATE_SUBCATEGORY_REQUEST = "INACTIVATE_SUBCATEGORY_REQUEST";
export const INACTIVATE_SUBCATEGORY_SUCCESS = "INACTIVATE_SUBCATEGORY_SUCCESS";
export const INACTIVATE_SUBCATEGORY_FAIL = "INACTIVATE_SUBCATEGORY_FAIL";
