export const GET_TABLES_REQUEST = "GET_TABLES_REQUEST";
export const GET_TABLES_SUCCESS = "GET_TABLES_SUCCESS";
export const GET_TABLES_FAIL = "GET_TABLES_FAIL";

export const ADD_TABLE_REQUEST = "ADD_TABLE_REQUEST";
export const ADD_TABLE_SUCCESS = "ADD_TABLE_SUCCESS";
export const ADD_TABLE_FAIL = "ADD_TABLE_FAIL";

export const UPDATE_TABLE_REQUEST = "UPDATE_TABLE_REQUEST";
export const UPDATE_TABLE_SUCCESS = "UPDATE_TABLE_SUCCESS";
export const UPDATE_TABLE_FAIL = "UPDATE_TABLE_FAIL";
